### ISSUE TITLE
Peer-to-code review 3/2/2022

### ISSUE THREAD

**Issue by oyelakinG9** [fherrerao/Capstone-Group-Project#44]
## Hi @fherrerao,  
 Good work so far. It was a nice ideal to split your codes into modules 👍👍.
 Good interface website ✔✔
 But I would recommend you update the `Likes` functionality every time users click it. 

<img src="https://www.serialminds.com/wp-content/uploads/2015/11/loser.gif" width="400" height="250" />

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀

**Comment by aimemalaika** [comment]
@fherrerao Good work so far. It was a nice idea to split your codes into modules 👍👍.
